//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTank_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbTankEntities : DbContext
    {
        public dbTankEntities()
            : base("name=dbTankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableTank> TableTank { get; set; }
    
        public virtual int SpEditSettings(Nullable<int> partankCapacity, Nullable<int> partankCapacityMax, Nullable<int> partankCapacityMin, Nullable<int> parliquidCapacity, Nullable<int> parliquidCapacityMin, Nullable<int> parliquidCapacityMax)
        {
            var partankCapacityParameter = partankCapacity.HasValue ?
                new ObjectParameter("partankCapacity", partankCapacity) :
                new ObjectParameter("partankCapacity", typeof(int));
    
            var partankCapacityMaxParameter = partankCapacityMax.HasValue ?
                new ObjectParameter("partankCapacityMax", partankCapacityMax) :
                new ObjectParameter("partankCapacityMax", typeof(int));
    
            var partankCapacityMinParameter = partankCapacityMin.HasValue ?
                new ObjectParameter("partankCapacityMin", partankCapacityMin) :
                new ObjectParameter("partankCapacityMin", typeof(int));
    
            var parliquidCapacityParameter = parliquidCapacity.HasValue ?
                new ObjectParameter("parliquidCapacity", parliquidCapacity) :
                new ObjectParameter("parliquidCapacity", typeof(int));
    
            var parliquidCapacityMinParameter = parliquidCapacityMin.HasValue ?
                new ObjectParameter("parliquidCapacityMin", parliquidCapacityMin) :
                new ObjectParameter("parliquidCapacityMin", typeof(int));
    
            var parliquidCapacityMaxParameter = parliquidCapacityMax.HasValue ?
                new ObjectParameter("parliquidCapacityMax", parliquidCapacityMax) :
                new ObjectParameter("parliquidCapacityMax", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpEditSettings", partankCapacityParameter, partankCapacityMaxParameter, partankCapacityMinParameter, parliquidCapacityParameter, parliquidCapacityMinParameter, parliquidCapacityMaxParameter);
        }
    
        public virtual ObjectResult<SpSelectSettings_Result> SpSelectSettings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpSelectSettings_Result>("SpSelectSettings");
        }
    }
}
