//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTank_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTank
    {
        public int id { get; set; }
        public int tankCapacity { get; set; }
        public int tankCapacityMax { get; set; }
        public int tankCapacityMin { get; set; }
        public int liquidCapacity { get; set; }
        public int liquidCapacityMin { get; set; }
        public int liquidCapacityMax { get; set; }
    }
}
